"""
Value store built from the same derived results as the tables.

Every number the prose cites is emitted here, as a LaTeX macro for the paper
(``\\val{<dataset>/<path>}``) and as JSON for the website, both from the same derived
results, so a single regeneration keeps figures, tables, and text in lockstep and a
cited value can never disagree with the table beside it.
"""

from __future__ import annotations

import json
from pathlib import Path

import polars as pl

from drift_happens.analysis.datasets import DATASETS, DatasetSpec
from drift_happens.analysis.plots import derive
from drift_happens.analysis.plots.names import FAMILY_LABELS, slice_label, slugify
from drift_happens.analysis.plots.tables import _humanize

_FROZEN_FAMILIES = (
    "image-transfer",
    "text-frozen-head",
    "text-frozen-head-regression",
)

_PREAMBLE = r"""% Generated by `drift analysis figures`; do not edit by hand.
% Read a value with \val{<dataset>/<path>}, e.g. \val{arxiv/model/tx_m/decay}.
% An unknown key stops the build rather than printing nothing.
\providecommand{\val}[1]{%
  \ifcsname valstore/#1\endcsname\csname valstore/#1\endcsname
  \else\errmessage{unknown value key: #1}\fi}"""

Pairs = list[tuple[str, str]]


def write_values(
    frame: pl.DataFrame, params: pl.DataFrame, tex_path: Path, json_path: Path
) -> None:
    """Write the value store as LaTeX macros and as JSON for every dataset."""
    sections: list[tuple[str, Pairs]] = []
    for dataset, spec in DATASETS.items():
        models, _ = derive.per_model_matrices(frame, dataset)
        if not models:
            continue
        cutoffs = derive.select_cutoffs(models[0].slices)
        sections.append(
            (spec.title, _dataset_pairs(dataset, spec, models, cutoffs, frame, params))
        )

    tex = [_PREAMBLE]
    for title, pairs in sections:
        tex.append(rf"% ---- {title} ----")
        tex += [_macro(key, value) for key, value in pairs]
    tex_path.parent.mkdir(parents=True, exist_ok=True)
    tex_path.write_text("\n".join(tex) + "\n")

    flat = {key: value for _, pairs in sections for key, value in pairs}
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(flat, indent=2, sort_keys=True) + "\n")


def _dataset_pairs(
    dataset: str,
    spec: DatasetSpec,
    models: list[derive.DriftMatrix],
    cutoffs: list[str],
    frame: pl.DataFrame,
    params: pl.DataFrame,
) -> Pairs:
    slices = models[0].slices
    return [
        *_facts(spec, models, slices, frame, dataset),
        *_counts(dataset, spec, params),
        *_per_model(spec, models),
        *_ranges(dataset, spec, models, params),
        *_per_family(dataset, spec, cutoffs, models, frame),
        *_family_means(dataset, spec, models, params),
        *_roster(dataset, spec, params),
    ]


def _facts(
    spec: DatasetSpec,
    models: list[derive.DriftMatrix],
    slices: tuple[str, ...],
    frame: pl.DataFrame,
    dataset: str,
) -> Pairs:
    """Counts and spans that describe the benchmark."""
    seeds = derive._eval_rows(frame, dataset).get_column("seed").n_unique()
    return [
        _pair(f"{spec.slug}/models", len(models)),
        _pair(f"{spec.slug}/cutoffs", len(slices)),
        _pair(f"{spec.slug}/seeds", seeds),
        _pair(f"{spec.slug}/cutoff-first", slice_label(slices[0], spec)),
        _pair(f"{spec.slug}/cutoff-last", slice_label(slices[-1], spec)),
    ]


def _counts(dataset: str, spec: DatasetSpec, params: pl.DataFrame) -> Pairs:
    """Model counts split into from-scratch architectures and frozen encoders."""
    rows = params.filter(pl.col("dataset") == dataset)
    frozen = rows.filter(pl.col("trainer_family").is_in(_FROZEN_FAMILIES)).height
    return [
        _pair(f"{spec.slug}/scratch-models", rows.height - frozen),
        _pair(f"{spec.slug}/frozen-models", frozen),
    ]


def _per_model(spec: DatasetSpec, models: list[derive.DriftMatrix]) -> Pairs:
    """In-distribution, future, and decay for every model."""
    pairs: Pairs = []
    for matrix in models:
        key = f"{spec.slug}/model/{matrix.model}"
        indist, future, decay = _scores(spec, matrix)
        pairs += [
            _pair(f"{key}/indist", _num(indist, spec)),
            _pair(f"{key}/future", _num(future, spec)),
            _pair(f"{key}/decay", _num(decay, spec)),
        ]
    return pairs


def _ranges(
    dataset: str,
    spec: DatasetSpec,
    models: list[derive.DriftMatrix],
    params: pl.DataFrame,
) -> Pairs:
    """Min and max over the scratch and frozen groups, for ``between x and y``
    claims."""
    family_of = _family_of(dataset, params)
    groups: dict[str, list[tuple[float, float, float]]] = {"scratch": [], "frozen": []}
    for matrix in models:
        group = (
            "frozen" if family_of.get(matrix.model) in _FROZEN_FAMILIES else "scratch"
        )
        groups[group].append(_scores(spec, matrix))
    pairs: Pairs = []
    for group, triples in groups.items():
        if not triples:
            continue
        for index, name in enumerate(("indist", "future", "decay")):
            values = [triple[index] for triple in triples]
            pairs += [
                _pair(f"{spec.slug}/{group}/{name}-min", _num(min(values), spec)),
                _pair(f"{spec.slug}/{group}/{name}-max", _num(max(values), spec)),
            ]
    return pairs


def _per_family(
    dataset: str,
    spec: DatasetSpec,
    cutoffs: list[str],
    models: list[derive.DriftMatrix],
    frame: pl.DataFrame,
) -> Pairs:
    """Future and decay per family at each reported cutoff, matching the family
    table."""
    pairs: Pairs = []
    for row in derive.family_rows(frame, dataset, models, cutoffs):
        family = slugify(FAMILY_LABELS.get(row.family, row.family)).lower()
        for cutoff, (future, decay) in zip(cutoffs, row.cells, strict=True):
            key = f"{spec.slug}/family/{family}/{slugify(cutoff)}"
            pairs += [
                _pair(f"{key}/future", _num(future, spec)),
                _pair(f"{key}/decay", _num(decay, spec)),
            ]
    return pairs


def _family_means(
    dataset: str,
    spec: DatasetSpec,
    models: list[derive.DriftMatrix],
    params: pl.DataFrame,
) -> Pairs:
    """Mean in-distribution, future, and decay over each family's models."""
    family_of = _family_of(dataset, params)
    members: dict[str, list[derive.DriftMatrix]] = {}
    for matrix in models:
        label = FAMILY_LABELS.get(family_of.get(matrix.model, ""), "")
        members.setdefault(slugify(label).lower(), []).append(matrix)
    pairs: Pairs = []
    for family, mats in members.items():
        scores = [_scores(spec, matrix) for matrix in mats]
        key = f"{spec.slug}/family/{family}"
        for index, name in enumerate(("indist", "future", "decay")):
            mean = sum(score[index] for score in scores) / len(scores)
            pairs.append(_pair(f"{key}/{name}", _num(mean, spec)))
    return pairs


def _roster(dataset: str, spec: DatasetSpec, params: pl.DataFrame) -> Pairs:
    """Trainable and total parameter counts per model."""
    pairs: Pairs = []
    for record in params.filter(pl.col("dataset") == dataset).iter_rows(named=True):
        key = f"{spec.slug}/param/{record['trainer']}"
        pairs += [
            _pair(f"{key}/trainable", _humanize(record["trainable"])),
            _pair(f"{key}/total", _humanize(record["total"])),
        ]
    return pairs


def _scores(
    spec: DatasetSpec, matrix: derive.DriftMatrix
) -> tuple[float, float, float]:
    indist = derive._diagonal_mean(matrix)
    future = derive._future_mean(matrix)
    decay = indist - future if spec.higher_is_better else future - indist
    return indist, future, decay


def _family_of(dataset: str, params: pl.DataFrame) -> dict[str, str]:
    return {
        row["trainer"]: row["trainer_family"]
        for row in params.filter(pl.col("dataset") == dataset).iter_rows(named=True)
    }


def _num(value: float, spec: DatasetSpec) -> str:
    return f"{value:{spec.value_fmt}}"


def _pair(key: str, value: object) -> tuple[str, str]:
    return key, str(value)


def _macro(key: str, value: str) -> str:
    return rf"\expandafter\def\csname valstore/{key}\endcsname{{{value}}}"
